spring:
  datasource:  # 配置数据库连接池
    url: jdbc:mysql://rm-2zec89875363ja0hj3o.mysql.rds.aliyuncs.com:3306/mybatis-plus?useUnicode=true&characterEncoding=utf8
    driver-class: com.mysql.cj.jdbc.Driver # 数据库驱动程序
    username: root1
    password: Lth13678812
