mybatis-plus:
  mapper-locations: classpath:mappers/*.xml # mapper文件扫描
  type-aliases-package: com.yhzm.bean # 实体类扫描
spring:          #表示该配置直接为Spring容器负责处理
　　datasource:
  　　type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
  　　driver-class-name: com.mysql.cj.jdbc.Driver       #配置MySQL的驱动程序类
  　　url: jdbc:mysql://rm-2zec89875363ja0hj3o.mysql.rds.aliyuncs.com:3306/mybatis-plus?useUnicode=true&characterEncoding=utf8
  　　username: root1
  　　password: Lth13678812
  　　dbcp2:
    　　min-idle: 5         #数据库连接池的最小维持连接数
    　　initial-size: 5     #初始化提供的连接数
    　　max-total: 5          #最大的连接数
    　　max-wait-millis: 200        #等待连接获取的最大超时时间